language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  include:
    - rust: nightly
      env: OPT="-Z package-features --package signalo --no-default-features"
    - rust: nightly
      env: OPT=""
  allow_failures:
    - rust: nightly
  fast_finish: true

script:
  - cargo build $OPT --verbose --all
  - cargo test $OPT --verbose --all
